name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 10.x

    - name: Run npm install
      run: npm install gulp

    # Build the solution
    - name: Build solution
      run: gulp bundle 

    # Package solution
    - name: Package
      run: gulp package-solution 

    # Publish artifact
    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sppkg-files
        path: "**/*.sppkg"
        if-no-files-found: error 